services:
  - type: web
    name: puniemu-wibwob
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: "8080"
      - key: PostgresConnectionString
        sync: false
      - key: IsWibWob
        value: "true"
      - key: GameVersion
        value: "4.0.6"
      - key: MaxConnections
        value: "100"
      - key: MaxCachedAccounts
        value: "100"
      - key: DataDownloadURL
        value: "0"
      - key: ServerName
        value: "WibWob FR"
      - key: EmailForAuthMessages
        value: ""
      - key: AppPasswordForAuthMessages
        value: ""
